package providers

var iconDefault = map[string]string{
		"sonarr": "tv",
		"radarr": "film",
		"lidarr": "music",
		"calibre": "book",
		"transmission": "progress-download",
		"sabnzbd": "progress-download",
		"deluge": "progress-download",
		"nzbget": "progress-download",
		"headend": "antenna",
		"ombi": "magnify",
		"tautulli": "chart-arc",
		"plexpi": "chart-arc",
		"sui": "home",
		"hydra": "cloud-search-outline",
		"hydrav2": "cloud-search-outline",
		"hydra2": "cloud-search-outline",
		"jackett": "cloud-search-outline",
		"jacket": "cloud-search-outline",
		"unraid": "server",
		"prometheus": "chart-bar-stacked",
		"prom": "chart-bar-stacked",
		"influx": "chart-bar-stacked",
		"influxdb": "chart-bar-stacked",
		"telegraf": "chart-bar-stacked",
		"grafana": "chart-bar-stacked",
		"plex": "plex",
		"emby": "play-box",
		"jellyfin": "play-box",
	}
