
name: Docker Rolling

on:
  push:
    branches:
      - latest

jobs:
  rolling-docker:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract Repo Owner
        shell: bash
        run: echo "##[set-output name=owner;]$(echo ${GITHUB_REPOSITORY%%/*} | tr '[:upper:]' '[:lower:]')"
        id: extract_owner
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - 
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.extract_owner.outputs.owner }}
          password: ${{ secrets.CR_PAT }}
      - 
        name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v6,linux/arm/v7,linux/386
          push: true
          tags: |
            ghcr.io/${{ steps.extract_owner.outputs.owner }}/sui:latest
            docker.io/${{ secrets.DOCKER_USERNAME }}/sui:latest
          no-cache: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          labels: |
            dev.sui.image.title=${{ github.event.repository.name }}
            dev.sui.image.description=${{ github.event.repository.description }}
            dev.sui.image.url=${{ github.event.repository.html_url }}
