name: CI

on:
  push:
    branches: 
      - latest
      - dev
      - v1
      - v2 
  pull_request:
    branches: 
      - dev

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Docker Login
        if: success() 
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${REGISTRY} --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Buildx
        if: success() 
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --file ./build/Dockerfile \
            --tag ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/sui:${GITHUB_REF##*/} \
            --output type=image,push=true .

